### PR TITLE
Update test_parser.py

### PR DESCRIPTION
**Pull request by blueraft**
Make test file path platform independent. Current solution only works on unix systems.

### CODE REVIEW

**Comment by ndaelman-hu** [comment]
Could you provide some context? What does this PR solve?

**Comment by blueraft** [comment]
I've updated the description

**Comment by ndaelman-hu** [comment]
> Current solution only works on unix systems.

I see... I run on UNIX. Do you want a review from a Windows user?
That aside, it all looks fine.

**Comment by blueraft** [comment]
> Do you want a review from a Windows user?

No, `os.path.join` should work fine.

**Review by ndaelman-hu — APPROVED** [review]

**Pull request merged**
